version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - unconvert
    - unparam
  settings:
    gocritic:
      disabled-checks:
        - unnamedResult
        - singleCaseSwitch
        - builtinShadowDecl
        - paramTypeCombine
        - docStub
        - octalLiteral
      enabled-tags:
        - diagnostic
        - style
    gosec:
      excludes:
        - G104
        - G301
        - G304
        - G306
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/evertonstz/go-workflows
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
