name: Build and release Go Project

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Cross compile
        run: |
          mkdir -p bin
          # Linux binaries
          GOOS=linux GOARCH=amd64 go build -o bin/server-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o bin/server-linux-arm64 .
          # macOS binaries
          GOOS=darwin GOARCH=amd64 go build -o bin/server-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o bin/server-darwin-arm64 .
          # Windows binaries
          GOOS=windows GOARCH=amd64 go build -o bin/server-windows-amd64.exe .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            This release includes:
            - Linux binaries (amd64, arm64)
            - macOS binaries (amd64, arm64)
            - Windows binary (amd64)
          files: |
            bin/server-linux-amd64
            bin/server-linux-arm64
            bin/server-darwin-amd64
            bin/server-darwin-arm64
            bin/server-windows-amd64.exe
