name: Build and release Go Project

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Cross compile and package
        run: |
          mkdir -p bin

          # Linux binaries
          GOOS=linux GOARCH=amd64 go build -o bin/go-workflows .
          tar -czvf bin/go-workflows-linux-amd64.tar.gz -C bin go-workflows
          GOOS=linux GOARCH=arm64 go build -o bin/go-workflows .
          tar -czvf bin/go-workflows-linux-arm64.tar.gz -C bin go-workflows

          # macOS binaries
          GOOS=darwin GOARCH=amd64 go build -o bin/go-workflows .
          tar -czvf bin/go-workflows-darwin-amd64.tar.gz -C bin go-workflows
          GOOS=darwin GOARCH=arm64 go build -o bin/go-workflows .
          tar -czvf bin/go-workflows-darwin-arm64.tar.gz -C bin go-workflows

          # Windows binaries
          GOOS=windows GOARCH=amd64 go build -o bin/go-workflows.exe .
          zip -j bin/go-workflows-windows-amd64.zip bin/go-workflows.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            This release includes:
            - Linux binaries (amd64, arm64)
            - macOS binaries (amd64, arm64)
            - Windows binary (amd64)
          files: |
            bin/go-workflows-linux-amd64.tar.gz
            bin/go-workflows-linux-arm64.tar.gz
            bin/go-workflows-darwin-amd64.tar.gz
            bin/go-workflows-darwin-arm64.tar.gz
            bin/go-workflows-windows-amd64.zip
