name: Update Homebrew Formula

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  update-formula:
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest

    steps:
      - name: Update Homebrew Formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          tap: evertonstz/homebrew-go-workflows
          formula: go-workflows
          tag: ${{ github.event.release.tag_name }}
          revision: ${{ github.sha }}

      - name: Notify Success or Error
        if: always()
        run: |
          CHANNEL="${{ secrets.NTFY_CHANNEL }}"
          if [ "${{ job.status }}" == "success" ]; then
            curl -H "Title: Homebrew Update Success" -d "Homebrew formula updated to ${{ github.event.release.tag_name }}" ntfy.sh/$CHANNEL
          else
            curl -H "Title: Homebrew Update Failure" -d "Homebrew formula update failed for ${{ github.event.release.tag_name }}" ntfy.sh/$CHANNEL
          fi
