name: Update Homebrew Formula

on:
  workflow_run:
    workflows: ["Build and release Go Project"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-formula:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Obter informações do release
        id: release_info
        run: |
          echo "TAG_NAME=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
          echo "BASE_URL=https://github.com/${{ github.repository }}/releases/download/${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      - name: Calcular SHA256
        id: sha256
        run: |
          for PLATFORM in linux-amd64 linux-arm64 darwin-amd64 darwin-arm64; do
            FILE="go-workflows-${PLATFORM}.tar.gz"
            curl -L -o $FILE ${{ env.BASE_URL }}/$FILE
            HASH=$(sha256sum $FILE | awk '{print $1}')
            echo "${PLATFORM}=${HASH}" >> sha256_hashes.txt
          done

      - name: Debug - Mostrar SHA256 calculados
        run: cat sha256_hashes.txt

      - name: Atualizar fórmula
        run: |
          FORMULA_PATH="Formula/go-workflows.rb"
          TAG_NAME="${{ env.TAG_NAME }}"
          
          sed -i "s|version \".*\"|version \"${TAG_NAME}\"|g" $FORMULA_PATH

          # Atualizar URLs e SHA256
          while IFS="=" read -r PLATFORM HASH; do
            URL="${{ env.BASE_URL }}/go-workflows-${PLATFORM}.tar.gz"
            sed -i "/${PLATFORM}/!b;n;c\        sha256 \"${HASH}\"" $FORMULA_PATH
            sed -i "s|url \".*${PLATFORM}.*\"|url \"${URL}\"|g" $FORMULA_PATH
          done < sha256_hashes.txt

      - name: Commitar atualizações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Formula/go-workflows.rb
          git commit -m "Atualizar fórmula Homebrew para ${{ env.TAG_NAME }}"
          git push
