name: Validate Workflows

on:
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Validate Workflow Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: ".github/workflows/**"
          files_separator: " "

      - name: List changed workflow files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed workflow files:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "  - $file"
          done

      - name: Validate YAML syntax
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Installing yamllint..."
          pip install yamllint

          echo "Validating YAML syntax..."
          exit_code=0

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Checking $file..."
            if yamllint -d relaxed "$file"; then
              echo "✅ $file - YAML syntax OK"
            else
              echo "❌ $file - YAML syntax errors found"
              exit_code=1
            fi
          done

          if [ $exit_code -eq 0 ]; then
            echo "✅ All workflow files have valid YAML syntax"
          else
            echo "❌ Some workflow files have YAML syntax errors"
            exit 1
          fi

      - name: Validate GitHub Actions syntax
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker://rhymond/github-action-validator:latest
        with:
          args: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Success summary
        if: success() && steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "🎉 All workflow validations passed!"
          echo "Validated files: ${{ steps.changed-files.outputs.all_changed_files }}"
