---
name: Validate Locale Files

"on":
  pull_request:
    paths:
      - "locales/*.json"
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  validate-locales:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed locale files
        id: changed-locales
        uses: tj-actions/changed-files@v44
        with:
          files: "locales/*.json"

      - name: Convert file list to comma-separated
        if: steps.changed-locales.outputs.any_changed == 'true'
        id: file-list
        run: |
          # Convert space-separated list to comma-separated, excluding schema.json
          files="${{ steps.changed-locales.outputs.all_changed_files }}"
          # Filter out schema.json since it's not a locale file
          filtered_files=""
          for file in $files; do
            if [[ "$file" != *"schema.json" ]]; then
              if [[ -z "$filtered_files" ]]; then
                filtered_files="$file"
              else
                filtered_files="$filtered_files,$file"
              fi
            fi
          done
          echo "files=$filtered_files" >> $GITHUB_OUTPUT
          echo "Locale files to validate: $filtered_files"

      - name: Validate JSON syntax and schema
        if: steps.changed-locales.outputs.any_changed == 'true' && steps.file-list.outputs.files != ''
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: locales/schema.json
          INPUT_JSONS: ${{ steps.file-list.outputs.files }}

      - name: Validate schema.json syntax
        if: steps.changed-locales.outputs.any_changed == 'true'
        run: |
          # Check if schema.json was changed and validate its syntax
          if echo "${{ steps.changed-locales.outputs.all_changed_files }}" | grep -q "schema.json"; then
            echo "Validating schema.json syntax..."
            if ! jq empty locales/schema.json > /dev/null 2>&1; then
              echo "❌ Invalid JSON syntax in locales/schema.json"
              exit 1
            fi
            echo "✅ Valid JSON syntax in locales/schema.json"
          fi

      - name: Validate key consistency across locale files
        if: steps.changed-locales.outputs.any_changed == 'true'
        run: |
          echo "Checking key consistency across locale files..."
          
          # Get all locale files (excluding schema.json)
          locale_files=$(find locales -name "*.json" ! -name "schema.json" | sort)
          
          if [ -z "$locale_files" ]; then
            echo "No locale files found to validate"
            exit 0
          fi
          
          # Count keys in each file and store results
          declare -A file_counts
          expected_count=""
          first_file=""
          
          for file in $locale_files; do
            if [ ! -f "$file" ]; then
              echo "File $file not found"
              continue
            fi
            
            # Count the number of keys in the JSON file
            count=$(jq 'keys | length' "$file")
            file_counts["$file"]=$count
            
            echo "File $file has $count keys"
            
            if [ -z "$expected_count" ]; then
              expected_count=$count
              first_file=$file
            elif [ "$count" -ne "$expected_count" ]; then
              echo "❌ Key count mismatch!"
              echo "  $first_file has $expected_count keys"
              echo "  $file has $count keys"
              echo "All locale files must have the same number of keys"
              exit 1
            fi
          done
          
          echo "✅ All locale files have consistent key counts ($expected_count keys each)"
