---
name: Validate Workflow Files

on:
  pull_request:
    paths:
      - ".github/workflows/**"
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write
  issues: write

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed workflow files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: ".github/workflows/**"

      - name: Debug workflow trigger
        run: |
          echo "Workflow triggered by PR #${{ github.event.number }}"
          echo "Changed files detected: ${{ steps.changed-files.outputs.any_changed }}"
          echo "All changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Changed workflow files count: ${{ steps.changed-files.outputs.all_changed_files_count }}"

      - name: Validate YAML syntax
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ${{ steps.changed-files.outputs.all_changed_files }}
          config_file: .yamllint

      - name: Validate GitHub Actions workflow syntax
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: SchemaStore/test@v1
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
