---
name: Validate Locale Files

"on":
  pull_request:
    paths:
      - "locales/*.json"
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  validate-locales:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed locale files
        id: changed-locales
        uses: tj-actions/changed-files@v44
        with:
          files: "locales/*.json"

      - name: Validate JSON syntax and schema
        if: steps.changed-locales.outputs.any_changed == 'true'
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: locales/schema.json
          INPUT_JSONS: ${{ steps.changed-locales.outputs.all_changed_files }}
